---

require:
- rubocop-rails
- rubocop-performance
- rubocop-rspec
- rubocop-rspec_rails
- rubocop-factory_bot

AllCops:
  NewCops: enable

Rails/UnknownEnv:
  Environments:
  - production
  - rc
  - test
  - development

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
